OUTPUT_DIR: "output/in1k_dap_r50"
MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-50"
  BACKBONE:
    CONV_BODY: "R-50-FPN"
  RESNETS:
    BACKBONE_OUT_CHANNELS: 256
  RPN:
    USE_FPN: True
    ANCHOR_STRIDE: (4, 8, 16, 32, 64)
    PRE_NMS_TOP_N_TRAIN: 2000
    PRE_NMS_TOP_N_TEST: 1000
    POST_NMS_TOP_N_TEST: 1000
    FPN_POST_NMS_TOP_N_TEST: 1000
  ROI_HEADS:
    USE_FPN: True
  ROI_BOX_HEAD:
    NUM_CLASSES: 1001
    POOLER_RESOLUTION: 7
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    POOLER_SAMPLING_RATIO: 2
    FEATURE_EXTRACTOR: "FPN2MLPFeatureExtractor"
    PREDICTOR: "FPNPredictor"
  # IGNORE_CLS_TEST: True
DATASETS:
  # 1,281,167 images from 1000 classes; bs 256 -> 5004.56 batches
  # TRAIN: ("imagenetcls_train_cam2xyxy",)
  TRAIN: ("imagenetcls_train_cam3nms8xyxy",)
  # 50,000 validation images
  # TEST: ("voc_2007_test","imagenetcls_test_cam3xyxy")
INPUT:
  # Multi-scale
  MIN_SIZE_TRAIN: (96,160,320,640)
  MIN_SIZE_TEST: 640
  # Single-scale
  # MIN_SIZE_TRAIN: (800,)
  # MAX_SIZE_TRAIN: 1333
  # MIN_SIZE_TEST: 800
  # MAX_SIZE_TEST: 1333
DATALOADER:
  SIZE_DIVISIBILITY: 32
SOLVER:
  WEIGHT_DECAY: 0.0001
  WARMUP_FACTOR: 0.01
  WARMUP_ITERS: 2000
  # BASE_LR: 0.002  # 4 gpus
  # IMS_PER_BATCH: 16
  # BASE_LR: 0.004  # 8 gpus
  # IMS_PER_BATCH: 32
  # BASE_LR: 0.08  # 8 gpus
  BASE_LR: 0.008  # 8 gpus
  IMS_PER_BATCH: 64
  # STEPS_EPOCH: (2.,)
  CHECKPOINT_EPOCH: 1
  MAX_EPOCH: 1.
  CHECKPOINT_EPOCH: 10
  LOG_PERIOD: 50
  TEST_PERIOD: 10000
TEST:
  IMS_PER_BATCH: 16
