OUTPUT_DIR: "output/in22k_dap_r101"
MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "pretrained_models/cls/model_r101_imagenet22k.old_format.pt"
  BACKBONE:
    CONV_BODY: "R-101-FPN"
  RESNETS:
    BACKBONE_OUT_CHANNELS: 256
    STRIDE_IN_1X1: False
  RPN:
    USE_FPN: True
    ANCHOR_STRIDE: (4, 8, 16, 32, 64)
    PRE_NMS_TOP_N_TRAIN: 2000
    PRE_NMS_TOP_N_TEST: 1000
    POST_NMS_TOP_N_TEST: 1000
    FPN_POST_NMS_TOP_N_TEST: 1000
    # FPN_POST_NMS_PER_BATCH: False  # default: True, which is a bug
  ROI_HEADS:
    USE_FPN: True
  ROI_BOX_HEAD:
    NUM_CLASSES: 21842  # 21841 + 1
    POOLER_RESOLUTION: 7
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    POOLER_SAMPLING_RATIO: 2
    FEATURE_EXTRACTOR: "FPN2MLPFeatureExtractor"
    PREDICTOR: "FPNPredictor"
  CLS_AGNOSTIC_BBOX_REG: True
  # IGNORE_CLS_TEST: True
DATASETS:
  # 14,000,000 images from 1000 classes. /64 -> ~218750
  TRAIN: ("TaxImageNet22kSplit64_cam2nms8xyxy",)
  # TEST: ("voc_2007_test",)
INPUT:
  PIXEL_MEAN: [0.485, 0.456, 0.406]
  TEST_PIXEL_MEAN: [0.485, 0.456, 0.406]
  PIXEL_STD: [0.229, 0.224, 0.225]
  TO_BGR255: False
  MIN_SIZE_TRAIN: (96,160,320,640)
DATALOADER:
  SIZE_DIVISIBILITY: 32
SOLVER:
  WEIGHT_DECAY: 0.00001  # better than 1e-4
  # BASE_LR: 0.002
  # IMS_PER_BATCH: 16  # 4 gpus, 1 node
  BASE_LR: 0.008
  IMS_PER_BATCH: 64  # 16 gpus, 4 node
  # BASE_LR: 0.032
  # IMS_PER_BATCH: 256  # 64 gpus, 16 nodes
  STEPS_EPOCH: ()
  MAX_EPOCH: 1.
  CHECKPOINT_EPOCH: 1
  # CHECKPOINT_PERIOD: 80000  # ~5 checkpoints
  LOG_PERIOD: 50
  TEST_PERIOD: 40000
  # WARMUP_FACTOR: 0.01
  # WARMUP_ITERS: 2000
TEST:
  # IMS_PER_BATCH: 8  # 4 gpus
  IMS_PER_BATCH: 32  # 16 gpus
  # IMS_PER_BATCH: 128  # 64 gpus
