OUTPUT_DIR: "output/in22k_cls_r101/coco"
MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "~output/model_r101_imagenet22k.old_format.pt"
  BACKBONE:
    CONV_BODY: "R-101-FPN"
  RESNETS:
    BACKBONE_OUT_CHANNELS: 256
    STRIDE_IN_1X1: False
  RPN:
    USE_FPN: True
    ANCHOR_STRIDE: (4, 8, 16, 32, 64)
    PRE_NMS_TOP_N_TRAIN: 2000
    PRE_NMS_TOP_N_TEST: 1000
    POST_NMS_TOP_N_TEST: 1000
    FPN_POST_NMS_TOP_N_TEST: 1000
  ROI_HEADS:
    USE_FPN: True
  ROI_BOX_HEAD:
    NUM_CLASSES: 81
    POOLER_RESOLUTION: 7
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    POOLER_SAMPLING_RATIO: 2
    FEATURE_EXTRACTOR: "FPN2MLPFeatureExtractor"
    PREDICTOR: "FPNPredictor"
DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST: ("coco_2017_val",)
INPUT:
  PIXEL_MEAN: [0.485, 0.456, 0.406]
  TEST_PIXEL_MEAN: [0.485, 0.456, 0.406]
  PIXEL_STD: [0.229, 0.224, 0.225]
  TO_BGR255: False
DATALOADER:
  SIZE_DIVISIBILITY: 32
SOLVER:
  # WEIGHT_DECAY: 0.0001
  WEIGHT_DECAY: 0.00001
  BASE_LR: 0.02
  STEPS: (60000, 80000)
  MAX_ITER: 90000
  IMS_PER_BATCH: 16
  CHECKPOINT_PERIOD: 100000
  LOG_PERIOD: 50
  TEST_PERIOD: 10000
TEST:
  IMS_PER_BATCH: 8
